Add "--native-steam-dir" option
lhark/truckersmp-cli pull request #135
Opened 2020-11-27 13:48 UTC by kakurasan

For users who don't save account credentials on their computers.

Note: We recommend that such users start Steam and login beforehand. Otherwise they would need to wait 99 seconds.

2020-11-28 14:21 UTC, Lucki requested changes
I guess this is for #133 and alike?

I still don't know how our check could have failed but at least this would give us some proper user fallback.

2020-11-28 14:21 UTC, Lucki commented on truckersmp_cli/utils.py
> +                continue
Instead of skipping everything we should add the path to our list so we can actually wait correctly.

2020-11-28 14:21 UTC, Lucki commented on README.md
> +(Not available)|`--native-steam-dir`|Choose native Steam installation, useful only if you use Proton and you don't save account credentials on this computer [Default: `auto`]
You may haven't noticed this but I have sorted the arguments alphabetically.
May be worth to rename both so they can group together.

Same in the argparser.

2020-11-29 02:29 UTC, kakurasan commented
> I still don't know how our check could have failed

I assumed that @TheStami checked "Don't save account credentials on this computer" in Steam configuration but not sure without providing @TheStami's configuration.

I'm using Ubuntu 20.10 without checking it and the autodetection is working.

> Instead of skipping everything we should add the path to our list so we can actually wait correctly.

When user checks that, our script can't detect the change of `loginusers.vdf` (= can't stop waiting even when the user logged in). So I recommend that such users start Steam and login beforehand.

2020-11-29 13:57 UTC, kakurasan commented
> our script can't detect the change of `loginusers.vdf`

I'm sorry, after checking "Don't save account credentials on this computer", `loginusers.vdf` was *created temporarily*. But Steam client might change the behavior in the future.

2020-12-14 11:12 UTC, Lucki approved these changes

2020-12-19 14:27 UTC, merged